---
- hosts: myServers
  become: yes
  vars:
    instance_count: 1

  tasks:

   
  - name: Including variables from files 
    include_vars: creds.yml 
  
  - name: Launching a set of instances
    ec2: 
      aws_access_key: "{{ aws_ak }}"
      aws_secret_key: "{{ aws_sk }}"
      keypair: "{{ my_keypair }}" 
      group: ec2-server
      instance_type: t2.micro
      image: "{{ default_image }}"
      wait: yes 
      region: "{{ ec2_region }}" 
      count: "{{ instance_count }}"
      vpc_subnet_id: "{{ ec2_subnet }}"
      assign_public_ip: yes 
    register: ec2

  - name: Adding new instances to group
    add_host:
      hostname: "{{ item.public_ip }}" 
      groupname: myServers
    with_items: "{{ ec2.instances }}" 

  - name: Waiting for SSH to come up before installing nginx
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"


- include: nginx_install.yml
 
...
